"""initial schema

Generated by Alembic autogenerate from drs/db/models.py, then made portable: boolean server
defaults use sa.true() / sa.false() so the same file runs on PostgreSQL and SQLite.

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 07:43:54.042617
"""

from alembic import op
import sqlalchemy as sa

import drs.db.types
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drs_access_log',
    sa.Column('log_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('logged_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('report_code', sa.String(length=50), nullable=True),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.CheckConstraint("action IN ('LOGIN', 'LOGOUT', 'VIEW', 'RUN', 'EXPORT_XLSX', 'EXPORT_CSV', 'EXPORT_TXT', 'BI_TOKEN')", name=op.f('ck_drs_access_log_action')),
    sa.CheckConstraint("status IN ('OK', 'DENIED', 'ERROR')", name=op.f('ck_drs_access_log_status')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_drs_access_log')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_access_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drs_access_log_logged_at'), ['logged_at'], unique=False)

    op.create_table('drs_audit_log',
    sa.Column('audit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('logged_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_key', sa.String(length=200), nullable=False),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_drs_audit_log')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drs_audit_log_logged_at'), ['logged_at'], unique=False)

    op.create_table('drs_datasource',
    sa.Column('datasource_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('datasource_code', sa.String(length=50), nullable=False),
    sa.Column('datasource_name', sa.String(length=200), nullable=False),
    sa.Column('db_type', sa.String(length=20), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.String(length=500), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('secret_ref', sa.String(length=1000), nullable=True),
    sa.Column('driver', sa.String(length=50), nullable=True),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("db_type IN ('mssql', 'postgresql', 'sqlite')", name=op.f('ck_drs_datasource_db_type')),
    sa.PrimaryKeyConstraint('datasource_id', name=op.f('pk_drs_datasource')),
    sa.UniqueConstraint('datasource_code', name=op.f('uq_drs_datasource_datasource_code')),
    sqlite_autoincrement=True
    )
    op.create_table('drs_report_group',
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('group_code', sa.String(length=50), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_drs_report_group')),
    sa.UniqueConstraint('group_code', name=op.f('uq_drs_report_group_group_code')),
    sqlite_autoincrement=True
    )
    op.create_table('drs_role',
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_drs_role')),
    sa.UniqueConstraint('role_code', name=op.f('uq_drs_role_role_code')),
    sqlite_autoincrement=True
    )
    op.create_table('drs_user',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', drs.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', drs.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_drs_user')),
    sa.UniqueConstraint('sso_subject', name=op.f('uq_drs_user_sso_subject')),
    sa.UniqueConstraint('username', name=op.f('uq_drs_user_username')),
    sqlite_autoincrement=True
    )
    op.create_table('drs_grant_group',
    sa.Column('grant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('can_export', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('can_refresh', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('granted_by', sa.String(length=100), nullable=True),
    sa.Column('granted_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (role_id IS NULL)', name=op.f('ck_drs_grant_group_one_principal')),
    sa.ForeignKeyConstraint(['group_id'], ['drs_report_group.group_id'], name=op.f('fk_drs_grant_group_group_id_drs_report_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['drs_role.role_id'], name=op.f('fk_drs_grant_group_role_id_drs_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['drs_user.user_id'], name=op.f('fk_drs_grant_group_user_id_drs_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grant_id', name=op.f('pk_drs_grant_group')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_grant_group', schema=None) as batch_op:
        batch_op.create_index('uq_drs_grant_group_role', ['group_id', 'role_id'], unique=True, postgresql_where=sa.text('role_id IS NOT NULL'), sqlite_where=sa.text('role_id IS NOT NULL'))
        batch_op.create_index('uq_drs_grant_group_user', ['group_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'), sqlite_where=sa.text('user_id IS NOT NULL'))

    op.create_table('drs_report',
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_code', sa.String(length=50), nullable=False),
    sa.Column('report_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('group_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('report_type', sa.String(length=10), nullable=False),
    sa.Column('datasource_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('design_uri', sa.String(length=1000), nullable=True),
    sa.Column('bi_dataset_table', sa.String(length=63), nullable=True),
    sa.Column('cache_ttl_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('serve_stale_on_error', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('max_rows', sa.Integer(), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.CheckConstraint("report_type IN ('GRID', 'HTML', 'BI')", name=op.f('ck_drs_report_report_type')),
    sa.ForeignKeyConstraint(['datasource_id'], ['drs_datasource.datasource_id'], name=op.f('fk_drs_report_datasource_id_drs_datasource')),
    sa.ForeignKeyConstraint(['group_id'], ['drs_report_group.group_id'], name=op.f('fk_drs_report_group_id_drs_report_group')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_drs_report')),
    sa.UniqueConstraint('report_code', name=op.f('uq_drs_report_report_code')),
    sqlite_autoincrement=True
    )
    op.create_table('drs_session',
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=10), nullable=False),
    sa.Column('created_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', drs.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.CheckConstraint("auth_method IN ('local', 'sso')", name=op.f('ck_drs_session_auth_method')),
    sa.ForeignKeyConstraint(['user_id'], ['drs_user.user_id'], name=op.f('fk_drs_session_user_id_drs_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_hash', name=op.f('pk_drs_session'))
    )
    op.create_table('drs_user_attribute',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('attr_name', sa.String(length=100), nullable=False),
    sa.Column('attr_value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['drs_user.user_id'], name=op.f('fk_drs_user_attribute_user_id_drs_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'attr_name', 'attr_value', name=op.f('pk_drs_user_attribute'))
    )
    op.create_table('drs_user_role',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['drs_role.role_id'], name=op.f('fk_drs_user_role_role_id_drs_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['drs_user.user_id'], name=op.f('fk_drs_user_role_user_id_drs_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_drs_user_role'))
    )
    op.create_table('drs_grant_report',
    sa.Column('grant_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('role_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('can_export', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('can_refresh', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('granted_by', sa.String(length=100), nullable=True),
    sa.Column('granted_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(user_id IS NULL) <> (role_id IS NULL)', name=op.f('ck_drs_grant_report_one_principal')),
    sa.ForeignKeyConstraint(['report_id'], ['drs_report.report_id'], name=op.f('fk_drs_grant_report_report_id_drs_report'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['drs_role.role_id'], name=op.f('fk_drs_grant_report_role_id_drs_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['drs_user.user_id'], name=op.f('fk_drs_grant_report_user_id_drs_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grant_id', name=op.f('pk_drs_grant_report')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_grant_report', schema=None) as batch_op:
        batch_op.create_index('uq_drs_grant_report_role', ['report_id', 'role_id'], unique=True, postgresql_where=sa.text('role_id IS NOT NULL'), sqlite_where=sa.text('role_id IS NOT NULL'))
        batch_op.create_index('uq_drs_grant_report_user', ['report_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'), sqlite_where=sa.text('user_id IS NOT NULL'))

    op.create_table('drs_report_column',
    sa.Column('column_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=10), nullable=True),
    sa.Column('display_format', sa.String(length=30), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('align', sa.String(length=10), nullable=True),
    sa.Column('is_visible', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_exported', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_sortable', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('footer_aggregate', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("align IS NULL OR align IN ('left', 'center', 'right')", name=op.f('ck_drs_report_column_align')),
    sa.CheckConstraint("data_type IS NULL OR data_type IN ('text', 'int', 'decimal', 'float', 'bool', 'date', 'datetime', 'time')", name=op.f('ck_drs_report_column_data_type')),
    sa.CheckConstraint("footer_aggregate IS NULL OR footer_aggregate IN ('sum', 'avg', 'count', 'min', 'max')", name=op.f('ck_drs_report_column_footer_aggregate')),
    sa.ForeignKeyConstraint(['report_id'], ['drs_report.report_id'], name=op.f('fk_drs_report_column_report_id_drs_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('column_id', name=op.f('pk_drs_report_column')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_report_column', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drs_report_column_report_id_field_name'), ['report_id', 'field_name'], unique=True)

    op.create_table('drs_report_lock',
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=False),
    sa.Column('locked_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['drs_report.report_id'], name=op.f('fk_drs_report_lock_report_id_drs_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id', 'cache_key', name=op.f('pk_drs_report_lock'))
    )
    op.create_table('drs_report_param',
    sa.Column('param_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('param_name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=10), nullable=False),
    sa.Column('input_kind', sa.String(length=12), server_default='input', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('default_value', sa.String(length=500), nullable=True),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('options_query', sa.Text(), nullable=True),
    sa.Column('options_datasource_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('multi_bind_mode', sa.String(length=10), server_default='expand', nullable=False),
    sa.Column('min_value', sa.String(length=50), nullable=True),
    sa.Column('max_value', sa.String(length=50), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('regex', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("data_type IN ('text', 'int', 'decimal', 'date', 'datetime', 'bool')", name=op.f('ck_drs_report_param_data_type')),
    sa.CheckConstraint("input_kind IN ('input', 'select', 'multiselect')", name=op.f('ck_drs_report_param_input_kind')),
    sa.CheckConstraint("multi_bind_mode IN ('expand', 'csv')", name=op.f('ck_drs_report_param_multi_bind_mode')),
    sa.ForeignKeyConstraint(['options_datasource_id'], ['drs_datasource.datasource_id'], name=op.f('fk_drs_report_param_options_datasource_id_drs_datasource')),
    sa.ForeignKeyConstraint(['report_id'], ['drs_report.report_id'], name=op.f('fk_drs_report_param_report_id_drs_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('param_id', name=op.f('pk_drs_report_param')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_report_param', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drs_report_param_report_id_param_name'), ['report_id', 'param_name'], unique=True)

    op.create_table('drs_report_row_filter',
    sa.Column('row_filter_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('column_name', sa.String(length=128), nullable=False),
    sa.Column('attr_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['drs_report.report_id'], name=op.f('fk_drs_report_row_filter_report_id_drs_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('row_filter_id', name=op.f('pk_drs_report_row_filter')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_report_row_filter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drs_report_row_filter_report_id_column_name'), ['report_id', 'column_name'], unique=True)

    op.create_table('drs_report_snapshot',
    sa.Column('snapshot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('params_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('columns_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('rows_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('source_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', drs.db.types.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', drs.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['drs_report.report_id'], name=op.f('fk_drs_report_snapshot_report_id_drs_report'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('snapshot_id', name=op.f('pk_drs_report_snapshot')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('drs_report_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drs_report_snapshot_expires_at'), ['expires_at'], unique=False)
    # Newest snapshot first for one (report, cache key). Autogenerate cannot render a DESC column.
    op.create_index(
        'ix_drs_report_snapshot_lookup', 'drs_report_snapshot',
        ['report_id', 'cache_key', sa.text('created_at DESC')], unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drs_report_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drs_report_snapshot_expires_at'))

    op.drop_index('ix_drs_report_snapshot_lookup', table_name='drs_report_snapshot')
    op.drop_table('drs_report_snapshot')
    with op.batch_alter_table('drs_report_row_filter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drs_report_row_filter_report_id_column_name'))

    op.drop_table('drs_report_row_filter')
    with op.batch_alter_table('drs_report_param', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drs_report_param_report_id_param_name'))

    op.drop_table('drs_report_param')
    op.drop_table('drs_report_lock')
    with op.batch_alter_table('drs_report_column', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drs_report_column_report_id_field_name'))

    op.drop_table('drs_report_column')
    with op.batch_alter_table('drs_grant_report', schema=None) as batch_op:
        batch_op.drop_index('uq_drs_grant_report_user', postgresql_where=sa.text('user_id IS NOT NULL'), sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index('uq_drs_grant_report_role', postgresql_where=sa.text('role_id IS NOT NULL'), sqlite_where=sa.text('role_id IS NOT NULL'))

    op.drop_table('drs_grant_report')
    op.drop_table('drs_user_role')
    op.drop_table('drs_user_attribute')
    op.drop_table('drs_session')
    op.drop_table('drs_report')
    with op.batch_alter_table('drs_grant_group', schema=None) as batch_op:
        batch_op.drop_index('uq_drs_grant_group_user', postgresql_where=sa.text('user_id IS NOT NULL'), sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index('uq_drs_grant_group_role', postgresql_where=sa.text('role_id IS NOT NULL'), sqlite_where=sa.text('role_id IS NOT NULL'))

    op.drop_table('drs_grant_group')
    op.drop_table('drs_user')
    op.drop_table('drs_role')
    op.drop_table('drs_report_group')
    op.drop_table('drs_datasource')
    with op.batch_alter_table('drs_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drs_audit_log_logged_at'))

    op.drop_table('drs_audit_log')
    with op.batch_alter_table('drs_access_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drs_access_log_logged_at'))

    op.drop_table('drs_access_log')
    # ### end Alembic commands ###
